### ISSUE TITLE
Ego File Converter error

### ISSUE THREAD

**Issue by Nicsal1** [ptasev/Ego-Engine-Modding#70]
when i try to convert a triggers_pit.xml file the program say this

Ego File Converter 2.1 ---
Processing triggers_pit.xml...
Failed to convert the file!
System.NotImplementedException: Converting xml node of type 1280 is not supported.
   at EgoEngineLibrary.Xml.XmlBinaryReader.ReadBxmlElement(XmlDocument doc)
   at EgoEngineLibrary.Xml.XmlBinaryReader.ReadBxmlElement(XmlDocument doc)
   at EgoEngineLibrary.Xml.XmlBinaryReader.ReadBxmlElement(XmlDocument doc)
   at EgoEngineLibrary.Xml.XmlBinaryReader.ReadBxmlElement(XmlDocument doc)
   at EgoEngineLibrary.Xml.XmlFile..ctor(Stream fileStream)
   at EgoFileConverter.Program.Convert(String f)
   at EgoFileConverter.Program.Main(String[] args)

Press any key to exit...

Downloading a mod from f1 2012 and converting the triggers.xml from the mod everything works fine. Thank you for your help

**Comment by ptasev** [comment]
Thanks for reporting. This is a bug most likely introduced in late 2016. I'll release a fix soon.

**Comment by Nicsal1** [comment]
Thank you so much

**Comment by ptasev** [comment]
Fixed in version 3.0.1

**Comment by Nicsal1** [comment]
Thank you so much.

Il lun 17 ott 2022, 06:54 Petar Tasev ***@***.***> ha scritto:
